In [ ]:
import pandas as pd
import numpy as np

In [ ]:
cell = pd.read_csv('/content/F_effective_cell_throughput.csv')

In [ ]:
cell.head(10)

,id,celltype,cuid,ecgi,fci,fileid,min5_effective_dl_cell_throughput,min5_effective_dl_cell_throughput_per_qci,min5_effective_ul_cell_throughput,min5_effective_ul_cell_throughput_per_qci,...,spare1,spare2,starttime,stoptime,total_cell_pdcp_dl_volume_qci,total_cell_pdcp_ul_volume_qci,vduname,vnfdid,vnflogicalid,vnftype
0,"6,023,785",Macro,2,2708756710728449,19,95cea6193407783308794bc34d79b472,-,-,-,-,...,0,0,"Jan 31, 2022 @ 23:55:00.000","Feb 1, 2022 @ 00:00:00.000",0,0,0,0,2,DU
1,"6,023,786",Macro,2,2708756710728449,19,95cea6193407783308794bc34d79b472,-,-,-,-,...,0,0,"Jan 31, 2022 @ 23:55:00.000","Feb 1, 2022 @ 00:00:00.000",0,0,0,0,2,DU
2,"6,023,787",Macro,2,2708756710728449,19,95cea6193407783308794bc34d79b472,-,-,-,-,...,0,0,"Jan 31, 2022 @ 23:55:00.000","Feb 1, 2022 @ 00:00:00.000",0,0,0,0,2,DU
3,"6,023,788",Macro,2,2708756710728449,19,95cea6193407783308794bc34d79b472,-,-,-,-,...,0,0,"Jan 31, 2022 @ 23:55:00.000","Feb 1, 2022 @ 00:00:00.000",0,0,0,0,2,DU
4,"6,023,789",Macro,2,2708756710728449,19,95cea6193407783308794bc34d79b472,-,-,-,-,...,0,0,"Jan 31, 2022 @ 23:55:00.000","Feb 1, 2022 @ 00:00:00.000",0,0,0,0,2,DU
5,"6,023,790",Macro,2,2708756710728449,19,95cea6193407783308794bc34d79b472,-,-,-,-,...,0,0,"Jan 31, 2022 @ 23:55:00.000","Feb 1, 2022 @ 00:00:00.000",0,0,0,0,2,DU
6,"6,023,791",Macro,2,2708756710728449,19,95cea6193407783308794bc34d79b472,-,-,-,-,...,0,0,"Jan 31, 2022 @ 23:55:00.000","Feb 1, 2022 @ 00:00:00.000",0,0,0,0,2,DU
7,"6,023,792",Macro,2,2708756710728449,19,95cea6193407783308794bc34d79b472,-,-,-,-,...,0,0,"Jan 31, 2022 @ 23:55:00.000","Feb 1, 2022 @ 00:00:00.000",0,0,0,0,2,DU
8,"6,023,793",Macro,2,2708756710728449,19,95cea6193407783308794bc34d79b472,-,-,-,-,...,0,0,"Jan 31, 2022 @ 23:55:00.000","Feb 1, 2022 @ 00:00:00.000",0,0,0,0,2,DU
9,"6,023,794",Macro,2,2708756710728449,19,95cea6193407783308794bc34d79b472,-,-,-,-,...,0,0,"Jan 31, 2022 @ 23:55:00.000","Feb 1, 2022 @ 00:00:00.000",0,0,0,0,2,DU

In [ ]:
cell.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46159 entries, 0 to 46158
Data columns (total 29 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   id                                         46159 non-null  object
 1   celltype                                   46159 non-null  object
 2   cuid                                       46159 non-null  int64
 3   ecgi                                       46159 non-null  int64
 4   fci                                        46159 non-null  int64
 5   fileid                                     46159 non-null  object
 6   min5_effective_dl_cell_throughput          46159 non-null  object
 7   min5_effective_dl_cell_throughput_per_qci  46159 non-null  object
 8   min5_effective_ul_cell_throughput          46159 non-null  object
 9   min5_effective_ul_cell_throughput_per_qci  46159 non-null  object
 10  nsdid                                      46159 non-null  int64
 11  qci                                        46159 non-null  int64
 12  rank                                       46159 non-null  object
 13  rat                                        46159 non-null  object
 14  rruid                                      46159 non-null  int64
 15  scheduler_active_time_dl_cell              46159 non-null  object
 16  scheduler_active_time_dl_qci               46159 non-null  object
 17  scheduler_active_time_ul_cell              46159 non-null  object
 18  scheduler_active_time_ul_qci               46159 non-null  object
 19  spare1                                     46159 non-null  int64
 20  spare2                                     46159 non-null  int64
 21  starttime                                  46159 non-null  object
 22  stoptime                                   46159 non-null  object
 23  total_cell_pdcp_dl_volume_qci              46159 non-null  object
 24  total_cell_pdcp_ul_volume_qci              46159 non-null  object
 25  vduname                                    46159 non-null  int64
 26  vnfdid                                     46159 non-null  int64
 27  vnflogicalid                               46159 non-null  int64
 28  vnftype                                    46159 non-null  object
dtypes: int64(11), object(18)
memory usage: 10.2+ MB

In [ ]:
pd.set_option('display.max_rows', None)

In [ ]:
active_ues = pd.read_csv('/content/F_Active_Ues.csv',sep = '\t' )

In [ ]:
active_ues.sample(5)

      starttime,"stoptime","vimid","nsdid","vnfdid","vnftype","vnfinstanceid","vduname","spare1","spare2","fci","ecgi","cuid","rruid","rat","qci","drbueactivedl","drbueactiveul","drbueactive","celltype","fileid","record_status","last_updated","network_group","id","shared_id","sync_id","rank","active_ues_with_data_beaerer","active_and_idle_ues","min5_active_ues_with_data_beaerer","min5_active_and_idle_ues","h_active_ues_with_data_beaerer","h_active_and_idle_ues","d_active_ues_with_data_beaerer","d_active_and_idle_ues","w_active_ues_with_data_beaerer","w_active_and_idle_ues","m_active_ues_with_data_beaerer","m_active_and_idle_ues"
57587  2022-01-26 16:50:00,"2022-01-26 16:55:00",NULL...
72185  2022-01-24 13:05:00,"2022-01-24 13:10:00",NULL...
10072  2022-01-25 05:15:00,"2022-01-25 05:20:00",NULL...
15834  2022-01-28 13:15:00,"2022-01-28 13:20:00",NULL...
58264  2022-01-27 00:15:00,"2022-01-27 00:20:00",NULL...

In [ ]:
df = pd.read_csv('CPE_Data.csv')

*   Deviation from mean behaviour of the UE in a particular location (type B)
*   High/Low TP when the UE is moving away from/towards the Cell (type C)
*   Variations in TP when Speed is low or close to 0 (type D)
*   Variation in TP when RF metrics are stable (type E)



*   - Change according to Rsrp, Rsrq, Sinr. If these three things are stable, but lots of fluctuations on the Rx Tx, issue 
- rsrp,  closer you are to the cell, the higher the value will be. -49 is high. -101 lowest
- RSRQ, varies between -7 and -20. that indicates quality. 
- SINR also quality metric. 30 good quality 0 or negative bad. measures interference
- fluctuates during the night when it shouldn't
- speed, 0 or close to 0, RF doesn’t change a lot and throughput performance fairly stable, if its low, low most of the time, if its high should be high most of the time, less than 1 or 5km/hr(very low), speed is the speed at which the boat is moving, if its moving away from the cell, throughput and RF reducing is expected.
- if im moving towards the centre of the cell, rf should become better and throughput as well.
- variations when the speed is close to 0 -> anomaly. less than 1 or 5km/hr(very low) shouldnt be too much variations in the throughput(stable)
- quality metrics explain if low value of throughput is expected or not. 
- it should be consistent. 


*   Élément de liste

In [ ]:
df.head()

,id,starttime,cellular_updated_at,rsrp,rsrq,rssi,signal,signal_quality,sinr,rx,tx,usage,longitude,latitude,speed,router_name,router_status,uptime,location_pin,location_isstatic,group_name,modem_name,modem_status,temperature,predicted_cell_rsrp,current_cell_name,location_timestamp
0,"235,621","Jan 24, 2022 @ 09:41:00.000","Jan 24, 2022 @ 09:41:00.000",-86,-14,-48,-86,14.5,14.5,"42,124","3,441","45,565",-2.678,58.119,5.335,MBX_Esvagt_Alba,online,"247,933","{\n ""coordinates"": [\n -2.678117,\n 58....",false,Moray East - Vestas,Cellular 2,Connected to 999 99,43.25,-95,VME22,"Jan 24, 2022 @ 09:40:28.000"
1,"235,622","Jan 24, 2022 @ 09:41:00.000","Jan 24, 2022 @ 09:41:00.000",-86,-14,-48,-86,14.5,14.5,"42,124","3,441","45,565",-2.678,58.119,5.562,MBX_Esvagt_Alba,online,"247,953","{\n ""coordinates"": [\n -2.678117,\n 58....",false,Moray East - Vestas,Cellular 2,Connected to 999 99,43.25,-95,VME22,"Jan 24, 2022 @ 09:40:28.000"
2,"235,623","Jan 24, 2022 @ 09:41:00.000","Jan 24, 2022 @ 09:41:00.000",-85,-16,-46,-85,17.1,17.1,"42,124","3,441","45,565",-2.678,58.119,5.562,MBX_Esvagt_Alba,online,"247,953","{\n ""coordinates"": [\n -2.678117,\n 58....",false,Moray East - Vestas,Cellular 1,Connected to 999 99,43.25,-95,VME22,"Jan 24, 2022 @ 09:40:28.000"
3,"235,620","Jan 24, 2022 @ 09:41:00.000","Jan 24, 2022 @ 09:41:00.000",-85,-16,-46,-85,17.1,17.1,"42,124","3,441","45,565",-2.678,58.119,5.335,MBX_Esvagt_Alba,online,"247,933","{\n ""coordinates"": [\n -2.678117,\n 58....",false,Moray East - Vestas,Cellular 1,Connected to 999 99,43.25,-95,VME22,"Jan 24, 2022 @ 09:40:28.000"
4,"235,618","Jan 24, 2022 @ 09:40:45.000","Jan 24, 2022 @ 09:40:45.000",-85,-11,-55,-85,17.0,17.0,"5,029","2,509","7,538",-2.678,58.119,5.327,MBX_Esvagt_Alba,online,"247,913","{\n ""coordinates"": [\n -2.678117,\n 58....",false,Moray East - Vestas,Cellular 1,Connected to 999 99,43.188,-95,VME22,"Jan 24, 2022 @ 09:40:28.000"

In [ ]:
df.loc[df['rsrp'] == -101]

,id,starttime,cellular_updated_at,rsrp,rsrq,rssi,signal,signal_quality,sinr,rx,tx,usage,longitude,latitude,speed,router_name,router_status,uptime,location_pin,location_isstatic,group_name,modem_name,modem_status,temperature,predicted_cell_rsrp,current_cell_name,location_timestamp
1625,"233,999","Jan 24, 2022 @ 05:07:47.000","Jan 24, 2022 @ 05:07:47.000",-101,-15,-66,-101,10.9,10.9,163,"1,163","1,326",-2.797,58.08,5.579,MBX_Esvagt_Alba,online,"231,537","{\n ""coordinates"": [\n -2.797107,\n 58....",false,Moray East - Vestas,Cellular 2,Connected to 999 99,42.625,-100,VME22,"Jan 24, 2022 @ 05:07:30.000"

In [ ]:
df.loc[df['rsrp'] == -49]

,id,starttime,cellular_updated_at,rsrp,rsrq,rssi,signal,signal_quality,sinr,rx,tx,usage,longitude,latitude,speed,router_name,router_status,uptime,location_pin,location_isstatic,group_name,modem_name,modem_status,temperature,predicted_cell_rsrp,current_cell_name,location_timestamp
15590,"220,034","Jan 22, 2022 @ 13:52:25.000","Jan 22, 2022 @ 13:52:25.000",-49,-9,-21,-49,25.0,25.0,"6,732","1,550","8,282",-2.683,58.206,0.517,MBX_Esvagt_Alba,online,"90,225","{\n ""coordinates"": [\n -2.683025,\n 58....",false,Moray East - Vestas,Cellular 1,Connected to 999 99,43.313,-60,VME21,"Jan 22, 2022 @ 13:52:30.000"
15819,"219,801","Jan 22, 2022 @ 13:13:26.000","Jan 22, 2022 @ 13:13:26.000",-49,-10,-20,-49,25.0,25.0,"7,077","5,711","12,788",-2.683,58.206,0.633,MBX_Esvagt_Alba,online,"87,879","{\n ""coordinates"": [\n -2.68277,\n 58.2...",false,Moray East - Vestas,Cellular 1,Connected to 999 99,43.563,-60,VME21,"Jan 22, 2022 @ 13:13:00.000"
15822,"219,804","Jan 22, 2022 @ 13:13:26.000","Jan 22, 2022 @ 13:13:26.000",-49,-10,-20,-49,25.0,25.0,"32,240","2,759","34,999",-2.683,58.206,0.633,MBX_Esvagt_Alba,online,"87,899","{\n ""coordinates"": [\n -2.68277,\n 58.2...",false,Moray East - Vestas,Cellular 1,Connected to 999 99,43.563,-60,VME21,"Jan 22, 2022 @ 13:13:00.000"

In [ ]:
df['current_cell_name'].value_counts()

VME23                 7860
VME32                 5802
VME11                 5504
VME33                 3644
VME13                 2985
VME12                  474
VME22                  369
VME21                  272
VME31                  156
Unknown/OutOfRange      50
Name: current_cell_name, dtype: int64

In [ ]:
df = df[df['current_cell_name'] != 'Unknown/OutOfRange']

In [ ]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
rsrp,27066.0,-86.375046,5.664928,-101.000,-90.00,-87.000,-83.000,-49.000
rsrq,27066.0,-11.157430,1.532988,-20.000,-12.00,-11.000,-10.000,-7.000
rssi,27066.0,-54.568573,5.737278,-68.000,-59.00,-55.000,-51.000,-14.000
signal,27066.0,-86.375046,5.664928,-101.000,-90.00,-87.000,-83.000,-49.000
signal_quality,27066.0,15.809665,2.497119,-7.400,14.20,16.000,17.500,25.000
sinr,27066.0,15.809665,2.497119,-7.400,14.20,16.000,17.500,25.000
longitude,27066.0,-2.748366,0.076354,-2.849,-2.81,-2.771,-2.685,-2.597
latitude,27066.0,58.197374,0.069177,58.071,58.11,58.217,58.248,58.298

In [ ]:
pd.set_option('display.max_columns', None)

In [ ]:
cell_names = df['current_cell_name'].unique()

In [ ]:
data = df[df['current_cell_name'] == cell_names[0]]
data.head()

,id,starttime,cellular_updated_at,rsrp,rsrq,rssi,signal,signal_quality,sinr,rx,tx,usage,longitude,latitude,speed,router_name,router_status,uptime,location_pin,location_isstatic,group_name,modem_name,modem_status,temperature,predicted_cell_rsrp,current_cell_name,location_timestamp
0,"235,621","Jan 24, 2022 @ 09:41:00.000","Jan 24, 2022 @ 09:41:00.000",-86,-14,-48,-86,14.5,14.5,"42,124","3,441","45,565",-2.678,58.119,5.335,MBX_Esvagt_Alba,online,"247,933","{\n ""coordinates"": [\n -2.678117,\n 58....",false,Moray East - Vestas,Cellular 2,Connected to 999 99,43.25,-95,VME22,"Jan 24, 2022 @ 09:40:28.000"
1,"235,622","Jan 24, 2022 @ 09:41:00.000","Jan 24, 2022 @ 09:41:00.000",-86,-14,-48,-86,14.5,14.5,"42,124","3,441","45,565",-2.678,58.119,5.562,MBX_Esvagt_Alba,online,"247,953","{\n ""coordinates"": [\n -2.678117,\n 58....",false,Moray East - Vestas,Cellular 2,Connected to 999 99,43.25,-95,VME22,"Jan 24, 2022 @ 09:40:28.000"
2,"235,623","Jan 24, 2022 @ 09:41:00.000","Jan 24, 2022 @ 09:41:00.000",-85,-16,-46,-85,17.1,17.1,"42,124","3,441","45,565",-2.678,58.119,5.562,MBX_Esvagt_Alba,online,"247,953","{\n ""coordinates"": [\n -2.678117,\n 58....",false,Moray East - Vestas,Cellular 1,Connected to 999 99,43.25,-95,VME22,"Jan 24, 2022 @ 09:40:28.000"
3,"235,620","Jan 24, 2022 @ 09:41:00.000","Jan 24, 2022 @ 09:41:00.000",-85,-16,-46,-85,17.1,17.1,"42,124","3,441","45,565",-2.678,58.119,5.335,MBX_Esvagt_Alba,online,"247,933","{\n ""coordinates"": [\n -2.678117,\n 58....",false,Moray East - Vestas,Cellular 1,Connected to 999 99,43.25,-95,VME22,"Jan 24, 2022 @ 09:40:28.000"
4,"235,618","Jan 24, 2022 @ 09:40:45.000","Jan 24, 2022 @ 09:40:45.000",-85,-11,-55,-85,17.0,17.0,"5,029","2,509","7,538",-2.678,58.119,5.327,MBX_Esvagt_Alba,online,"247,913","{\n ""coordinates"": [\n -2.678117,\n 58....",false,Moray East - Vestas,Cellular 1,Connected to 999 99,43.188,-95,VME22,"Jan 24, 2022 @ 09:40:28.000"

In [ ]:
mean_lat =df['latitude'].mean()
mean_long = df['longitude'].mean()

std_lat = df['latitude'].std()
std_lat = df['longitude'].std()

In [ ]:
mean_lat

58.197263128774715

In [ ]:
std_lat

0.07629045534187315